// automatically generated by the FlatBuffers compiler, do not modify

package com.bss.flatbuffer.dept;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FBBook extends Table {
	public static FBBook getRootAsFBBook(ByteBuffer _bb) {
		return getRootAsFBBook(_bb, new FBBook());
	}

	public static FBBook getRootAsFBBook(ByteBuffer _bb, FBBook obj) {
		_bb.order(ByteOrder.LITTLE_ENDIAN);
		return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
	}

	public void __init(int _i, ByteBuffer _bb) {
		bb_pos = _i;
		bb = _bb;
	}

	public FBBook __assign(int _i, ByteBuffer _bb) {
		__init(_i, _bb);
		return this;
	}

	public String bookId() {
		int o = __offset(4);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer bookIdAsByteBuffer() {
		return __vector_as_bytebuffer(4, 1);
	}

	public String authorId() {
		int o = __offset(6);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer authorIdAsByteBuffer() {
		return __vector_as_bytebuffer(6, 1);
	}

	public String authorDesc() {
		int o = __offset(8);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer authorDescAsByteBuffer() {
		return __vector_as_bytebuffer(8, 1);
	}

	public byte genre() {
		int o = __offset(10);
		return o != 0 ? bb.get(o + bb_pos) : 0;
	}

	public static int createFBBook(FlatBufferBuilder builder, int bookIdOffset, int authorIdOffset,
			int authorDescOffset, byte genre) {
		builder.startObject(4);
		FBBook.addAuthorDesc(builder, authorDescOffset);
		FBBook.addAuthorId(builder, authorIdOffset);
		FBBook.addBookId(builder, bookIdOffset);
		FBBook.addGenre(builder, genre);
		return FBBook.endFBBook(builder);
	}

	public static void startFBBook(FlatBufferBuilder builder) {
		builder.startObject(4);
	}

	public static void addBookId(FlatBufferBuilder builder, int bookIdOffset) {
		builder.addOffset(0, bookIdOffset, 0);
	}

	public static void addAuthorId(FlatBufferBuilder builder, int authorIdOffset) {
		builder.addOffset(1, authorIdOffset, 0);
	}

	public static void addAuthorDesc(FlatBufferBuilder builder, int authorDescOffset) {
		builder.addOffset(2, authorDescOffset, 0);
	}

	public static void addGenre(FlatBufferBuilder builder, byte genre) {
		builder.addByte(3, genre, 0);
	}

	public static int endFBBook(FlatBufferBuilder builder) {
		int o = builder.endObject();
		return o;
	}
}
