// automatically generated by the FlatBuffers compiler, do not modify

package com.bss.flatbuffer.dept;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FBStudent extends Table {
	public static FBStudent getRootAsFBStudent(ByteBuffer _bb) {
		return getRootAsFBStudent(_bb, new FBStudent());
	}

	public static FBStudent getRootAsFBStudent(ByteBuffer _bb, FBStudent obj) {
		_bb.order(ByteOrder.LITTLE_ENDIAN);
		return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
	}

	public void __init(int _i, ByteBuffer _bb) {
		bb_pos = _i;
		bb = _bb;
	}

	public FBStudent __assign(int _i, ByteBuffer _bb) {
		__init(_i, _bb);
		return this;
	}

	public int studentId() {
		int o = __offset(4);
		return o != 0 ? bb.getInt(o + bb_pos) : 0;
	}

	public String studentName() {
		int o = __offset(6);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer studentNameAsByteBuffer() {
		return __vector_as_bytebuffer(6, 1);
	}

	public String address() {
		int o = __offset(8);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer addressAsByteBuffer() {
		return __vector_as_bytebuffer(8, 1);
	}

	public byte favSubject() {
		int o = __offset(10);
		return o != 0 ? bb.get(o + bb_pos) : 0;
	}

	public static int createFBStudent(FlatBufferBuilder builder, int studentId, int studentNameOffset,
			int addressOffset, byte favSubject) {
		builder.startObject(4);
		FBStudent.addAddress(builder, addressOffset);
		FBStudent.addStudentName(builder, studentNameOffset);
		FBStudent.addStudentId(builder, studentId);
		FBStudent.addFavSubject(builder, favSubject);
		return FBStudent.endFBStudent(builder);
	}

	public static void startFBStudent(FlatBufferBuilder builder) {
		builder.startObject(4);
	}

	public static void addStudentId(FlatBufferBuilder builder, int studentId) {
		builder.addInt(0, studentId, 0);
	}

	public static void addStudentName(FlatBufferBuilder builder, int studentNameOffset) {
		builder.addOffset(1, studentNameOffset, 0);
	}

	public static void addAddress(FlatBufferBuilder builder, int addressOffset) {
		builder.addOffset(2, addressOffset, 0);
	}

	public static void addFavSubject(FlatBufferBuilder builder, byte favSubject) {
		builder.addByte(3, favSubject, 0);
	}

	public static int endFBStudent(FlatBufferBuilder builder) {
		int o = builder.endObject();
		return o;
	}
}
